Finalize comment form as a proof of concept in method page
th-koeln-intia/portal.intia.de pull request #16
Opened 2021-09-22 13:15 UTC by INTIA-Netlify-CMS

2021-09-22 14:34 UTC, MarcSchmidt requested changes
- Bitte nochmal drüberschauen und Testkommentare & Daten entfernen.

2021-09-22 14:34 UTC, MarcSchmidt commented on _layouts/post.html
> +  {{ page.date | date_to_string }} {% assign author = site.authors | where: 'name', page.author | first %} {% if author %} -
Das scheint noch nicht zu klappen.

2021-09-22 14:34 UTC, MarcSchmidt commented on _layouts/post.html
>    <p>Veröffentlicht: {{ page.date | date: "%b %-d, %Y" }} von {{ page.author }}</p>
Muss Weg, wenn oben die Autoren schon stehen

2021-09-22 14:34 UTC, MarcSchmidt commented on _data/comments/entry1627395100071.yml
> +_id: 8fdc8480-eee4-11eb-92fd-c141e86f6720
Bitte die Testkommentare dann entfernen.

2021-09-22 14:34 UTC, MarcSchmidt commented on _layouts/staff.html
> +--- layout: default ---
Wo wird das genutzt?

2021-09-22 14:34 UTC, MarcSchmidt commented on admin/config.yml
> +# config.yml
Das sind CMS sachen, die gehören nicht zu den Kommentaren.

2021-09-22 14:34 UTC, MarcSchmidt commented on staticman.yml
> +  name: "janseidler.github.io"
Anpassen.

2021-09-28 10:15 UTC, MarcSchmidt requested changes

2021-09-28 10:15 UTC, MarcSchmidt commented on _includes/comment-form.html
> +
Wird das hier benötigt? Font-Awesome ist ja bereits im header importiert?

2021-09-28 10:15 UTC, MarcSchmidt commented on _includes/comment-form.html
> +  <link rel="stylesheet" type="text/css" href="smart-forms.css">
Was macht dieses css? und wo liegt es.

2021-09-28 10:15 UTC, MarcSchmidt commented on _layouts/staff.html
> +--- layout: default ---
Wo wird das genutzt?

2021-09-28 10:15 UTC, MarcSchmidt commented on collections/_authors/jseidler.md
> +short_name: jseidler
Wird aktuell nicht im Code benutzt oder?

2021-09-28 10:15 UTC, MarcSchmidt commented on collections/_authors/map-layout-author-name-mschmidt-display_name-marc-schmidt-position-head-researcher-body-marc-is-a-lively-marc.md
> +---
Diese datei hat einen interessanten Namen, wird aber vorallem nicht genutzt.

2021-09-28 10:33 UTC, INTIA-Netlify-CMS commented on collections/_authors/map-layout-author-name-mschmidt-display_name-marc-schmidt-position-head-researcher-body-marc-is-a-lively-marc.md
> +---
xD

2021-09-28 10:58 UTC, MarcSchmidt commented on _includes/comment-form.html
> +<div class="smart-wrap">
Wo wird diese CSS-Klasse definiert?
Ich hab das auf anhieb nicht gefunden.

2021-09-28 14:12 UTC, MarcSchmidt commented on _includes/comment-form.html
> +    <div class="form-header header-blue">
Diese CSS-Klassen sind nicht definiert?

2021-09-28 14:12 UTC, MarcSchmidt commented on _includes/comment-form.html
> +      <div class="section">
Probier das mal aus, damit das richtig formatiert ist mit dem icon (ähnlich sollte auch für die anderen gelten):
<div class="section">
        <label class="field">
          <label class="label">Name</label>
          <div class="control has-icons-left">
            <input type="text" name="fields[name]" id="name" class="input is-primary"
                 placeholder="(Optional) Name eingeben..." value="Anonymer Mensch">
            <span class="icon is-small is-left"><i class="fa fa-user"></i></span>
          </div>
        </label>
      </div><!-- end section -->

2021-09-29 14:37 UTC, MarcSchmidt approved these changes

2021-09-29 14:37 UTC, merged